routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $pages=\App\Page::get();
    return view('index',['pages'=>$pages]);
    //return view('welcome');
});



Route::get('/about123', function () {

    return view('about');
});
Route::post('signup','AuthController@signUp')->name('signup');
Route::post('signin','AuthController@signIn')->name('signin');
Route::get('activate/account/{email}','AuthController@activateAccount')->name('activateAccount');
Route::post('forgot/password/','AuthController@forgotPassword')->name('forgotPassword');
Route::get('reset/password/{email}','AuthController@resetPassword')->name('resetPassword');



Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard','UserController@userDashboard')->name('userDashboard');
});


Route::group(['namespace' => 'admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {

Route::get('','AdminController@index')->name('admin');

Route::post('/login','AdminController@login')->name('adminLogin');

Route::get('/dashboard','AdminController@dashboard')->name('dashboard');
Route::get('/Pages','PageController@pages')->name('pages');
Route::get('/add/page','PageController@addPage')->name('addPage');
Route::post('/store/page','PageController@storePage')->name('storePage');
Route::get('/edit/{id}/page','PageController@editPage')->name('editPage');
Route::post('/update/page','PageController@updatePage')->name('updatePage');
Route::get('/view/{id}/page','PageController@viewPage')->name('viewPage');

Route::get('/media','MediaController@index')->name('media');
Route::get('/add/media','MediaController@addMedia')->name('addMedia');
Route::post('/store/media','MediaController@storeMedia')->name('storeMedia');
Route::get('/edit/{id}/media','MediaController@editMedia')->name('editMedia');
Route::post('/update/media','MediaController@updateMedia')->name('updateMedia');
Route::get('/view/{id}/media','MediaController@viewMedia')->name('viewMedia');

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

//Route::get('{slug}', ['uses' => 'PageController@getPage'])->where('slug', '([A-Za-z0-9\-\/]+)');
//Route::get('/{slug}', array('as' => 'page.show', 'uses' => 'PageController@getPage'));

Route::get('aboutus','AboutusController@index')->name('aboutus');

resources/views/admin/addmedia.blade.php
@extends('layouts.main')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <!-- About Me Box -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="col-md-10">
                            <h3 class="box-title"> Add Media</h3>
                        </div>
                        <div class="col-md-2 ">
                            <a href="javascript:void(0)" onclick="window.history.back();" class="btn btn-block btn-primary btn-sm">Back</a>

                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- form start -->
                    <form action="{{route('admin.storeMedia')}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="box-body">

                            <div class="row">
                                <div class="col-xs-12 {{ $errors->has('title') ? 'has-error':'' }}">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control" name="title" placeholder="Enter Title" value="{{old('title')}}">
                                        @if($errors->has('title'))
                                        <span class="help-block">{{$errors->first('title')}}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 {{ $errors->has('description') ? 'has-error':'' }}">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea type="text" class="form-control" name="description" placeholder="Description"> {{old('description')}}</textarea>
                                        @if($errors->has('description'))
                                            <span class="help-block">{{$errors->first('description')}}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-6 {{ $errors->has('link') ? 'has-error':'' }}">
                                    <div class="form-group">
                                        <label for="link">Link</label>
                                        <input type="text" class="form-control" name="link" placeholder="Enter Link" value="{{old('link')}}">
                                        @if($errors->has('link'))
                                        <span class="help-block">{{$errors->first('link')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-xs-6 {{ $errors->has('media_date') ? 'has-error':'' }}">
                                    <div class="form-group">
                                        <label for="media_date">Date</label>
                                        <input type="text" class="form-control" name="media_date" id="media_date" placeholder="Enter Date" value="{{old('media_date')}}">
                                        @if($errors->has('media_date'))
                                            <span class="help-block">{{$errors->first('media_date')}}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 {{ $errors->has('upload_type') ? 'has-error':'' }}">
                                <label for="description">Upload Type</label>
                                <!-- radio -->
                                <div class="form-group">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="upload_type" id="upload_type" class="upload_type" value="1" checked>
                                            Image
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="upload_type" id="upload_type" class="upload_type" value="2">
                                            Youtube Link
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-6 image-div {{ $errors->has('image') ? 'has-error':'' }}">
                                <div class="form-group">
                                    <label for="image">Image</label>
                                    <input type="file" class="form-control" name="image" placeholder="" value="{{old('image')}}">
                                    @if($errors->has('image'))
                                    <span class="help-block">{{$errors->first('image')}}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6 youtube-link-div {{ $errors->has('youtube_link') ? 'has-error':'' }}" style="display: none;">
                                <div class="form-group">
                                    <label for="youtube_link">Youtube Link</label>
                                    <input type="text" class="form-control" name="youtube_link" placeholder="Enter Youtube Link" value="{{old('youtube_link')}}">
                                    @if($errors->has('youtube_link'))
                                        <span class="help-block">{{$errors->first('youtube_link')}}</span>
                                    @endif
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
            <!--/.col (left) -->

        </div>

    </section><!-- /.content -->

</div>
<!-- /.content-wrapper -->
@endsection

@section('js')
<script type="text/javascript">
    $(document).ready(function () {

        $('.upload_type').change(function(){
            var upload_type = $(this).val();
            if(upload_type == 1){
                $('.image-div').show();
                $('.youtube-link-div').hide();
            } else {
                $('.image-div').hide();
                $('.youtube-link-div').show();
            }
        });

        $('#media_date').datepicker({
            format: 'yyyy-mm-dd'
        });

    });
</script>
@endsection

resources/views/admin/addpage.blade.php
@extends('layouts.main')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <!-- About Me Box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <div class="col-md-10">
                                <h3 class="box-title"> Add New Page</h3>
                            </div>
                            <div class="col-md-2 ">
                                <a href="javascript:void(0)" onclick="window.history.back();" class="btn btn-block btn-primary btn-sm">Back</a>

                            </div>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <!-- form start -->
                        <form action="{{route('admin.storePage')}}" method="post" enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="box-body">

                                <div class="row">
                                    <div class="col-xs-6 {{ $errors->has('page_name') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Page Name</label>
                                            <input type="text" class="form-control" name="page_name" placeholder="Enter Page Name" value="{{old('page_name')}}">
                                            @if($errors->has('page_name'))
                                                <span class="help-block">{{$errors->first('page_name')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-xs-6 {{ $errors->has('title') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Title</label>
                                            <input type="text" class="form-control" name="title" placeholder="Enter Page Title" value="{{old('title')}}">
                                            @if($errors->has('title'))
                                            <span class="help-block">{{$errors->first('title')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-6 {{ $errors->has('slug') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Slug</label>
                                            <input type="text" class="form-control" name="slug" placeholder="Enter Slug" value="{{old('slug')}}">
                                            @if($errors->has('slug'))
                                                <span class="help-block">{{$errors->first('slug')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-xs-6 {{ $errors->has('meta_title') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Meta Title</label>
                                            <input type="text" class="form-control" name="meta_title" placeholder="Enter Meta Title" value="{{old('meta_title')}}">
                                            @if($errors->has('meta_title'))
                                                <span class="help-block">{{$errors->first('meta_title')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-6 {{ $errors->has('meta_keyword') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Meta keyword</label>
                                            <textarea type="text" class="form-control" name="meta_keyword" placeholder="Enter Meta Keyword">{{old('meta_keyword')}}</textarea>
                                            @if($errors->has('meta_keyword'))
                                            <span class="help-block">{{$errors->first('meta_keyword')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-xs-6 {{ $errors->has('meta_description') ? 'has-error':'' }}">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Meta Description</label>
                                            <textarea type="text" class="form-control" name="meta_description" placeholder="Enter Meta Keyword"> {{old('meta_description')}}</textarea>
                                            @if($errors->has('meta_description'))
                                            <span class="help-block">{{$errors->first('meta_description')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-4 {{ $errors->has('banner_image') ? 'has-error':'' }}">
                                    <div class="form-group">
                                        <label for="banner_image">Banner Image</label>
                                        <input type="file" class="form-control" name="banner_image" placeholder="" value="{{old('banner_image')}}">
                                        @if($errors->has('banner_image'))
                                            <span class="help-block">{{$errors->first('banner_image')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 ">
                                        <label for="exampleInputEmail1">Page Content</label>
                                            <textarea id="page_content" name="page_content" rows="10" cols="80">
                            {{old('page_content')}}                    </textarea>
                                    </div>
                                </div>

                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->

                </div>
                <!--/.col (left) -->

            </div>

        </section><!-- /.content -->

    </div>
    <!-- /.content-wrapper -->
@endsection

@section('js')
<script>
    $(function () {
        $('#example1').DataTable({

        })

        CKEDITOR.replace('page_content');
        CKEDITOR.editorConfig = function( config ) {
            config.extraPlugins = 'preview';
        };
    })
</script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Don't Wish You Had | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset("assets//bower_components/bootstrap/dist/css/bootstrap.min.css")}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset("assets//bower_components/font-awesome/css/font-awesome.min.css")}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset("assets//bower_components/Ionicons/css/ionicons.min.css")}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("assets//dist/css/AdminLTE.min.css")}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset("assets//plugins/iCheck/square/blue.css")}}">




    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="javascript:void(0)"><b>Don't Wish </b>You Had</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible">
                <h4><i class="icon fa fa-ban"></i> {{session()->get('error')}} </h4>
            </div>
        @endif
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="{{route('admin.adminLogin')}}" method="post">
            {{csrf_field()}}

            <div class="form-group has-feedback {{ $errors->has('email') ? 'has-error':'' }}">

                <input type="email" name="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                @if($errors->has('email'))
                    <span class="help-block">{{$errors->first('email')}}</span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('password') ? 'has-error':'' }}">
                <input type="password" class="form-control" name="password" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                @if($errors->has('password'))
                    <span class="help-block">{{$errors->first('password')}}</span>
                @endif
            </div>


            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>


        <!-- /.social-auth-links -->

        {{--<a href="#">I forgot my password</a><br>--}}
        {{--<a href="register.html" class="text-center">Register a new membership</a>--}}

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{asset('assets//bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('assets//bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- iCheck -->
<script src="{{asset('assets//plugins/iCheck/icheck.min.js')}}"></script>


<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
</body>
</html>

resources/views/admin/media.blade.php
@extends('layouts.main')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- About Me Box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <div class="col-md-10">
                                <h3 class="box-title" style="margin-top: 5px;"> List Of Medias</h3>
                            </div>

                            <div class="col-md-2 ">
                                <a href="{{ route('admin.addMedia') }}" class="btn btn-block btn-primary btn-sm">Add Media</a>
                            </div>

                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Title</th>
                            <th>Link</th>
                            <th>Date</th>
                            <th>Status </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($media as $m)
                            <tr>
                                <td>{{$m->id}}</td>
                                <td>{{$m->title}}</td>
                                <td>{{$m->link}}</td>
                                <td>{{$m->media_date}}</td>
                                <td>
                                    @if($m->status == 1) Active @else De-Active @endif</td>
                                <td class="text-center" width="140px">
                                    <a href="{{route('admin.viewMedia',['id' => $m->id])}}" class="viewicon"> <i class="fa fa-eye fa-2x" aria-hidden="true"></i></a>
                                    <a href="{{route('admin.editMedia',['id' => $m->id])}}" class="editicon"> <i class="fa fa-pencil-square fa-2x margin-r-15 margin-l-15" aria-hidden="true"></i></a>
                                    <a href="#" class="deleteicon deleteMedia"  data-val="{{ $m->id }}"> <i class="fa fa-trash fa-2x " aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Title</th>
                            <th>Link</th>
                            <th>Date</th>
                            <th>Status </th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </section><!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable({

            })

        })
    </script>
@endsection

resources/views/admin/pages.blade.php
@extends('layouts.main')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- About Me Box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <div class="col-md-10">
                                <h3 class="box-title" style="margin-top: 5px;"> List Of Pages</h3>
                            </div>

                            <div class="col-md-2 ">
                                <a href="{{route('admin.addPage')}}" class="btn btn-block btn-primary btn-sm">Add New Page</a>
                            </div>

                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th>Title</th>
                            <th>Status </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($pages as $page)
                            <tr>
                                <td>{{$page->id}}</td>
                                <td>{{$page->name}}</td>
                                <td>{{$page->slug}}</td>
                                <td>{{$page->title}}</td>
                                <td>
                                    @if($page->status == 1) Active @else De-Active @endif</td>
                                <td class="text-center" width="140px">
                                    <a href="{{route('admin.viewPage',['id' => $page->id])}}" class="viewicon"> <i class="fa fa-eye fa-2x" aria-hidden="true"></i></a>
                                    <a href="{{route('admin.editPage',['id' => $page->id])}}" class="editicon"> <i class="fa fa-pencil-square fa-2x margin-r-15 margin-l-15" aria-hidden="true"></i></a>
                                    <a href="#" class="deleteicon deletepage"  data-val="{{ $page->id }}"> <i class="fa fa-trash fa-2x " aria-hidden="true"></i></a>
                                </td>
                            </tr>

                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th>Title</th>
                            <th>Status </th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </section><!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('js')
<script>
    $(function () {
        $('#example1').DataTable({

        })

    })
</script>
@endsection